### ISSUE TITLE
UnityプロジェクトをGitHubにプッシュすることができない

### ISSUE THREAD

**Issue by Parasuatene** [ohshimatani/AcceLance#2]
UnityプロジェクトをGitHub上にプッシュしようとしたところ、容量が大きくプッシュできないというエラーが出た。
by @ohshimatani

**Comment by Parasuatene** [comment]
@ohshimatani 
プッシュできなかった時に表示されたエラーメッセージを書いてくれると嬉しい。

**Comment by ohshimatani** [comment]
```
remote: error: Trace: bec75c87c01244a408c8e181414cd8fc9f608867d38079ecb443bdc4d8a02989
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File KanjiShooting/Library/PackageCache/com.unity.burst@1.6.6/.Runtime/hostmac/lld is 106.20 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: **Large files detected. You may want to try Git Large File Storage** - https://git-lfs.github.com.
To https://github.com/ohshimatani/AcceLance.git
 ! [remote rejected]   main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/ohshimatani/AcceLance.git'
```
こんな感じです。
100MBを超えるものはpushできないそう...

**Comment by ohshimatani** [comment]
## 困っていること

UnityのプロジェクトをGitHubにpushできない。

## 原因

100MBを超えるファイルがプロジェクト上に存在する。

（`KanjiShooting/Library/PackageCache/com.unity.burst@1.6.6/.Runtime/hostmac/lld`）

## 試したこと

- `git LFS(Large File Storage)`を使う
    - 使用方法：[[https://support-ja.backlog.com/hc/ja/articles/360038329474-Git-LFSの使用方法](https://support-ja.backlog.com/hc/ja/articles/360038329474-Git-LFS%E3%81%AE%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)](https://support-ja.backlog.com/hc/ja/articles/360038329474-Git-LFS%E3%81%AE%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
    - 使用方法２：[https://qiita.com/ikmski/items/5cc8b8832336b8d85429](https://qiita.com/ikmski/items/5cc8b8832336b8d85429)
    - 公式：[https://git-lfs.github.com/](https://git-lfs.github.com/)
- Unity内でAPK拡張ファイル（OBB）を使う→Unity2021.3ではサポートされていなかったため、不可能
    - 設定方法@ver2018：[https://dolphinetech.com/unity/unity-android-morethan100mb/](https://dolphinetech.com/unity/unity-android-morethan100mb/)
    - ver2018（可能）：[https://docs.unity3d.com/ja/2018.4/Manual/android-OBBsupport.html](https://docs.unity3d.com/ja/2018.4/Manual/android-OBBsupport.html)
    - ver2021（不可能）：[https://docs.unity3d.com/ja/2021.3/Manual/android-OBBsupport.html](https://docs.unity3d.com/ja/2021.3/Manual/android-OBBsupport.html)

## git LFSとは
公式サイトより
> Git Large File Storage (LFS) replaces large files such as audio samples, videos, datasets, and graphics with text pointers inside Git, while storing the file contents on a remote server like [[GitHub.com](http://github.com/)](http://github.com/) or GitHub Enterprise.
> 

日本語

> Git Large File Storage（LFS）は、オーディオサンプル、ビデオ、データセット、グラフィックスなどの大きなファイルをGit内のテキストポインターに置き換え、ファイルの内容をGitHub.comやGitHubEnterpriseなどのリモートサーバーに保存します。
> 

gitは100MBを超えたファイルをpushできない。→git LFSでは指定したファイルを（ざっくりいうと）小さくしてpushできるようにしてくれる。（？）

**Comment by ohshimatani** [comment]
## これからの方針
容量の大きかったファイル（<100MB）は`Library/PackageCache/~`とキャッシュが絡んでいそうなので、不要なファイルの可能性あり。
ファイルの正体を突きとめる方針で調査を続ける。

**Comment by ohshimatani** [comment]
### 状況報告
以下の理由により、そもそも`Library/PackageCache/~`自体削除してもよさそうだったが、`.gitignore`の書き方に問題があったかもしれないので、`.gitignore`ファイルの書き方を見直す。
---
https://joyplot.com/documents/unity-library-cache/
に

> Library フォルダ自体を削除しても、必要なファイルはプロジェクト起動時に再度生成され、実行時必要なキャッシュも随時作られるため問題ない
との記述があったため。

**Comment by ohshimatani** [comment]
## 状況報告
本リポジトリにおけるルートファイルは`/KanjiShooting/Library/~`のようになっているのに対して、
`.gitignore`には
`/[Ll]ibrary`
のように除外対象を書いていたため、うまく`.gitignore`が機能していなかった模様。
それらを
`/KanjiShooting/[Ll]ibrary`
のように書き換えたが、まだうまくいかない。

## 原因
無視したいファイルも既にステージングされ、gitの追跡対象となっていたから。
## 解決策
`git rm --cached <FILE NAME>`
によって、追跡対象から外す。
## つまづき
`git rm --cached KanjiShooting/`
と実行しても、
`fatal: not removing 'KanjiShooting/' recursively without -r`
とエラーが出る。
